---
title: "Question3"
output: html_document
---

```{r}
library(tidyverse)
library(ggthemes)
```

```{r}
transport <- read_csv("https://ourworldindata.org/grapher/co2-emissions-transport.csv")

co2 <- read_csv('data/data_raw/owid_co2.csv')

energy <- read_csv('data/data_raw/owid_energy.csv')
```

```{r}
transport_cr <- transport |>
  rename(
    country        = 1,   # usually "Entity"
    iso_code       = 2,   # usually "Code"
    year           = 3,   # "Year"
    transport_co2  = 4    # emissions from transport, tonnes
  ) |>
  filter(country == "Costa Rica")
```

```{r}
cr_transport <- co2 |>
  filter(country == "Costa Rica", year >= 1990) |>
  select(country, iso_code, year, co2, co2_per_capita, population) |>
  left_join(transport_cr,
            by = c("country", "iso_code", "year")) |>
  mutate(
    # co2 is in *million* tonnes; transport_co2 is in tonnes
    transport_share_total = if_else(!is.na(co2) & co2 > 0,
                                    transport_co2 / (co2 * 1e6),
                                    NA_real_),
    transport_co2_pc      = transport_co2 / population,
    non_transport_co2_pc  = ((co2 * 1e6) - transport_co2) / population
  )

```

```{r fig.height=6, fig.width=10}

cr_trans_plot <- cr_transport |>
  filter(!is.na(transport_share_total),
         year >= 1990)

p3 <- ggplot(cr_trans_plot,
                  aes(x = year)) +
  geom_line(
    aes(y = transport_share_total * 100),
    colour = "#D55E00",
    linewidth = 1.1
  ) +
  geom_hline(yintercept = 0, linetype = "dotted", colour = "grey70") +
  labs(
    title = "Transport’s share of Costa Rica’s CO\u2082 emissions",
    x = "Year",
    y = "Transport share of total CO\u2082 (%)"
  ) +
  theme_clean(base_size = 12) +
  theme(
    panel.grid.minor = element_blank()
  )

p3
```

```{r fig.height=6, fig.width=10}
cr_pc_long <- cr_transport |>
  filter(!is.na(transport_co2_pc),
         year >= 1990) |>
  select(year, transport_co2_pc, non_transport_co2_pc) |>
  pivot_longer(
    cols      = c(transport_co2_pc, non_transport_co2_pc),
    names_to  = "sector",
    values_to = "co2_pc"
  ) |>
  mutate(
    sector = recode(
      sector,
      transport_co2_pc     = "Transport",
      non_transport_co2_pc = "All other sectors"
    )
  )

p4 <- ggplot(cr_pc_long,
               aes(x = year, y = co2_pc, colour = sector)) +
  geom_line(linewidth = 1.1) +
  scale_colour_manual(values = c(
    "Transport"         = "#D55E00",
    "All other sectors" = "#0072B2"
  )) +
  labs(
    title = "CO\u2082 per capita from transport vs other sectors",
    x = "Year",
    y = "Tonnes CO\u2082 per person",
    colour = NULL
  ) +
  theme_clean(base_size = 12) +
  theme(
    legend.position = "bottom",
    panel.grid.minor = element_blank()
  )
p4
```
